-- Tylko rozszerzenia PostGIS
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_topology;
CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;

-- Modyfikacje dla systemu weryfikacji zdjęć
ALTER TABLE "ZDJECIA_RYB" ALTER COLUMN zlowiona_ryba_id DROP NOT NULL;
ALTER TABLE "ZDJECIA_RYB" ADD COLUMN IF NOT EXISTS status INTEGER DEFAULT 0;
ALTER TABLE "ZDJECIA_RYB" ADD COLUMN IF NOT EXISTS moderator_id BIGINT;
ALTER TABLE "ZDJECIA_RYB" ADD COLUMN IF NOT EXISTS verified_at TIMESTAMP;
ALTER TABLE "ZDJECIA_RYB" ADD COLUMN IF NOT EXISTS species_id BIGINT;
ALTER TABLE "ZDJECIA_RYB" ADD COLUMN IF NOT EXISTS length_cm FLOAT;